site_name: Documentação LFBagYourDreams

nav:
  - Página Inicial: index.md
  - Documento:
    - Visão do Produto e Projeto:
      - 1. Cenário Atual do Cliente e do Negócio: "documento-visao/cenario-atual.md"
      - 2. Solução Proposta: "documento-visao/solucao-proposta.md"
      - 3. Estratégias de Engenharia de Software: "documento-visao/estrategias.md"
      - 4. Engenharia de Requisitos: "documento-visao/eng.requisitos.md"
      - 5. Cronogramas e Entregas: "documento-visao/cronograma.md"
      - 6. Interação entre Equipe e cliente: "documento-visao/interacao.md"
      - 7. Requisitos de Software: "documento-visao/req.software.md"
      - 8. DoR e DoD: "documento-visao/dor_dod.md"
      - 9. Backlog de Produto: "documento-visao/backlog.md"
    - Histórico de versões do documento: "documento-visao/historico-versoes.md"
    - Referências Bibliograficas: "documento-visao/referencias.md"
  - Atas:
    - Ata dia 19/04/2025: "atas/ata_reuniao_19_04_25.md"
    - Ata dia 03/05/2025: "atas/ata_reuniao_03_05_25.md"
    - Ata dia 19/06/2025: "atas/ata_reuniao_19_06_25.md"
  - Lições aprendidas:
    - Unidade 1: "documento-visao/licoes-aprendidas/licoes-U1.md"
    - Unidade 2: "documento-visao/licoes-aprendidas/licoes-U2.md"
    - Unidade 3: "documento-visao/licoes-aprendidas/licoes-U3.md"
  - Vídeo Apresentação:
    - Unidade 1: "apresentacoes/apresentacao1.md"
    - Unidade 2: "apresentacoes/apresentacao2.md"
    - Unidade 3: "apresentacoes/apresentacao3.md"
  - Estudo de Caso:
    - User Story Mapping: "estudo-de-caso/USM.md"
    - PBB & BDD: "estudo-de-caso/pbb_bdd.md"
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt

  palette:
    - scheme: default
      toggle:
        icon: material/globe-light
        name: Dark mode
      primary: black
      accent: black
    - scheme: slate
      toggle:
        icon: material/globe-light-outline
        name: Light mode
      primary: white
      accent: black

markdown_extensions:
  - attr_list

extra_css:
  - css/custom.css