name: Run Python Tests

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configuring python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Running tests with pytest
      run: pytest backend
